# Generated by Django 5.0.6 on 2024-05-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='UserIcons/'),
        ),
    ]
