# Generated by Django 5.0.6 on 2024-05-28 04:29

import Account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=Account.utils.CustomUpload()),
        ),
    ]
